In [2]:
# 导入numpy模块
import numpy as np

In [8]:
# 创建 Python 列表
data = [1, 2, 3, 4, 5]
# 转换为 NumPy 数组
arr = np.array(data)

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 嵌套创建二维数组
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(arr2d)
# 💡 NumPy 中二维数组就相当于「矩阵」，支持行列运算。
print("这是二维数组中的第一行第三列",arr2d[0,2])

[[1 2 3]
 [4 5 6]]
3
