In [37]:
#导入numpy
import numpy as np
#创建一个一维数组
arr = np.array([1, 2, 3, 4, 5])


1. Ndarray数组所有元素的数据类型相同、数据地址连续，批量操作数组元素时速度更快，而list中元素的数据类型可能不同，需要通过寻址的方式找到下一个元素。
2. Ndarray数组支持广播机制，矩阵运算时不需要写for循环。
3. 底层主要使用C语言实现，运行速度远高于Python代码。

In [38]:
# 实现 a + 1 的运算
# 使用python语法不支持对列表进行加1操作
# list 的 + 1 必须视同for循环
a_list = [1, 2, 3, 4, 5]
print(a_list)
for i in range(len(a_list)):
    a_list[i] += 1
print(a_list)
# 输出: [2, 3, 4, 5, 6]   


[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]


In [39]:
# 使用Ndarray实现完成对数组中的每一个元素进行+1的操作
arr = np.array([1, 2, 3, 4, 5])
# Numpy数组可以直接进行+1操作，他会令数组中的所有元素都去进行+1的操作
arr +=1
print(arr)

[2 3 4 5 6]


In [40]:
# 实现 a +b 的运算
# 使用list完成两个列表元素的加法
a  = [1, 2, 3]
b  = [4, 5, 6]
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print("这是合并后的数组",c)
# 输出: [5, 7, 9]


这是合并后的数组 [5, 7, 9]


In [41]:
# 使用Ndarray完成两个数组的加法
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print("这是合并后的数组",c)

这是合并后的数组 [5 7 9]


In [42]:
# array 函数创建Ndarray数组
# array函数的参数
numpy_array = np.array(object = [1,2,3,4,5,6], dtype=None, copy=True, order='K', subok=False, ndmin=0)
print(numpy_array)

[1 2 3 4 5 6]


- 1.object：表示要转换为数组的数据，可以是列表元组数组等可迭代对象
- 2.dtype：可以指定数组的数据类型，如果未指定，则根据输入数据自动推断
- 3.copy：如果为TRUE，则赋值输入数据；如果为false，则只有必要时才复制，这意味着如果object已经是一个Numpy数组并且满足dtype要求，则不会创建数据的副本，默认为true
- 4.order：指定多维数组在内存中的存储顺序，'C'表示按行优先存储，'F'表示按列优先存储，'A'表示按输入数据的顺序存储，'K'表示尽可能保持输入数据的顺序
- 5.subok：如果为true，则生成的数组将使用输入数组的子类类型；如果为false，则生成的数组将始终是基类Numpy数组
- 6.ndmin：指定生成数组的最小维数，如果输入数据的维数小于ndmin，则在前面添加新的轴以满足最小维数要求


In [43]:
# 1️⃣ object：要转换为数组的数据
# 可以是列表、元组、嵌套列表等
a = np.array([1, 2, 3])
print("1. object:", a)
# 2️⃣ dtype：指定数组的数据类型
b = np.array([1.2,2.3,3.4], dtype=int)
print("\n2.dtype 制定类型为 int:", b)
# 3️⃣ copy：是否复制数据
c_source = np.array([1,2,3])
c = np.array(c_source, copy=False)  #不复制
# 浅拷贝？
c_source[0] = 99  # 改变原数组
print("\n3.copy = False 时 :", c)  # 视图也改变

d_source = np.array([1,2,3])
d = np.array(d_source, copy=True)  # 复制
# 深拷贝？
d_source[0] = 88  # 改变原数组
print("\n3.copy = True 时 :", d)  # 视图不变
# 4️⃣ order：指定内存存储顺序
e_c = np.array([[1,2,3],[4,5,6]], order='C')  # 按行存储
e_f = np.array([[1,2,3],[4,5,6]], order='F')  # 按列存储
print("\n4.order = 'C' 时:\n", e_c,"\n 元素线性顺序为：[1, 2, 3, 4, 5, 6]")
print("\n4.order = 'F' 时:\n", e_f,"\n 元素线性顺序为：[1, 4, 2, 5, 3, 6]")
# 5️⃣ subok：是否使用子类
class MyArray(np.ndarray):
    pass

x = np.array([1, 2, 3]).view(MyArray)
f1 = np.array(x, subok=True)   # 保留子类
f2 = np.array(x, subok=False)  # 转回普通 ndarray
print("\n5. subok=True：类型 ->", type(f1))
print("   subok=False：类型 ->", type(f2))

# 6️⃣ ndmin：指定最小维数
g = np.array([1, 2, 3], ndmin=3)
print("\n6. ndmin=3：shape ->", g.shape)
print(g)

1. object: [1 2 3]

2.dtype 制定类型为 int: [1 2 3]

3.copy = False 时 : [99  2  3]

3.copy = True 时 : [1 2 3]

4.order = 'C' 时:
 [[1 2 3]
 [4 5 6]] 
 元素线性顺序为：[1, 2, 3, 4, 5, 6]

4.order = 'F' 时:
 [[1 2 3]
 [4 5 6]] 
 元素线性顺序为：[1, 4, 2, 5, 3, 6]

5. subok=True：类型 -> <class '__main__.MyArray'>
   subok=False：类型 -> <class 'numpy.ndarray'>

6. ndmin=3：shape -> (1, 1, 3)
[[[1 2 3]]]


- arrange 函数创建Ndarray数组
- numpy.arrange(start=0, stop, step=1, dtype=None)
1. start: 可选参数，表示数组的起始值。 默认值为0
2. stop: 必须参数，表示数组的结束值（不包含该值）
3. step：可选参数，表示相邻两个值的差值，默认值为1。
4. dtype: 可选参数，表示返回数组的数据类型，如果没有指定，则根据其他参数推断数据类型