In [2]:
# 导入numpy模块
import numpy as np

In [8]:
# 创建 Python 列表
data = [1, 2, 3, 4, 5]
# 转换为 NumPy 数组
arr = np.array(data)

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 嵌套创建二维数组
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(arr2d)
# 💡 NumPy 中二维数组就相当于「矩阵」，支持行列运算。
print("这是二维数组中的第一行第三列",arr2d[0,2])

[[1 2 3]
 [4 5 6]]
3


In [10]:
import numpy as np
#  内置函数创建数组
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
full = np.full((2, 2), 9)
eye = np.eye(3)
arange_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

print("\nzeros:\n", zeros)
print("ones:\n", ones)
print("full:\n", full)
print("eye:\n", eye)
print("arange:\n", arange_arr)
print("linspace:\n", linspace_arr)


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
full:
 [[9 9]
 [9 9]]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange:
 [0 2 4 6 8]
linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#  随机数组
rand = np.random.rand(2, 3)
randint_arr = np.random.randint(0, 10, (2, 3))
print("\nrand:\n", rand)
print("randint:\n", randint_arr)

NameError: name 'np' is not defined

In [ ]:
#  数组属性
arr_attr = np.array([[1, 2, 3], [4, 5, 6]])
print("\n维度数:", arr_attr.ndim)
print("形状:", arr_attr.shape)
print("元素总数:", arr_attr.size)
print("数据类型:", arr_attr.dtype)

In [5]:
#  类型转换
arr_float = np.array([1.5, 2.8, 3.2])
arr_int = arr_float.astype(int)
print("\n类型转换示例:")
print("原数组:", arr_float)
print("转换后:", arr_int)

NameError: name 'np' is not defined

In [6]:
#  一维索引
a = np.array([10, 20, 30, 40, 50])
print("\n原数组:", a)
print("a[0]:", a[0])
print("a[-1]:", a[-1])
print("a[1:4]:", a[1:4])
print("a[:3]:", a[:3])
print("a[::2]:", a[::2])

NameError: name 'np' is not defined

In [7]:
#  二维索引
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("\n二维数组:\n", b)
print("b[0,0]:", b[0, 0])
print("b[1,2]:", b[1, 2])
print("b[2,:]:", b[2, :])
print("b[:,1]:", b[:, 1])

NameError: name 'np' is not defined

In [8]:
# 切片与视图
c = np.array([1, 2, 3, 4, 5])
d = c[1:4]
d[:] = 0
print("\n修改切片视图后的原数组:", c)

# 复制切片
e = c[1:4].copy()
e[:] = 9
print("深拷贝不影响原数组:")
print("c:", c)
print("e:", e)

NameError: name 'np' is not defined

In [9]:
#  花式索引
a = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print("\n花式索引结果:", a[idx])

b = np.arange(12).reshape(3, 4)
print("二维花式索引:", b[[0, 2], [1, 3]])

NameError: name 'np' is not defined

In [11]:
#  基本算术运算
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print("\n加法:", a + b)
print("减法:", a - b)
print("乘法:", a * b)
print("除法:", b / a)


加法: [11 22 33 44]
减法: [ -9 -18 -27 -36]
乘法: [ 10  40  90 160]
除法: [10. 10. 10. 10.]


In [12]:
# 数组与标量
arr = np.array([1, 2, 3, 4, 5])
print("\n标量乘法:", arr * 2)
print("标量加法:", arr + 10)


标量乘法: [ 2  4  6  8 10]
标量加法: [11 12 13 14 15]


In [13]:
#  通用函数 ufunc
arr = np.array([0, 1, 2, 3])
print("\n平方根:", np.sqrt(arr))
print("指数:", np.exp(arr))
print("正弦:", np.sin(arr))
print("对数:", np.log(arr + 1))

#  广播机制
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
print("\n广播结果:\n", a + b)


平方根: [0.         1.         1.41421356 1.73205081]
指数: [ 1.          2.71828183  7.3890561  20.08553692]
正弦: [0.         0.84147098 0.90929743 0.14112001]
对数: [0.         0.69314718 1.09861229 1.38629436]

广播结果:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [14]:
#  逻辑比较
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print("\n相等判断:", a == b)
print("大于判断:", a > b)
print("逻辑与:", np.logical_and(a > 0, b < 3))

#  统计运算
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("\n总和:", arr.sum())
print("均值:", arr.mean())
print("最大值:", arr.max())
print("最小值:", arr.min())
print("标准差:", arr.std())
print("方差:", arr.var())
print("按列求和:", arr.sum(axis=0))
print("按行求和:", arr.sum(axis=1))


相等判断: [False  True False]
大于判断: [False False  True]
逻辑与: [ True  True  True]

总和: 21
均值: 3.5
最大值: 6
最小值: 1
标准差: 1.707825127659933
方差: 2.9166666666666665
按列求和: [5 7 9]
按行求和: [ 6 15]


In [ ]:
# 矩阵乘法
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("\n矩阵乘法:\n", np.dot(a, b))
print("使用 @ 运算符:\n", a @ b)

#  其他常用函数
arr = np.array([10, 5, 8, 5, 10])
print("\n去重:", np.unique(arr))
print("排序:", np.sort(arr))
print("排序索引:", np.argsort(arr))
print("元素范围限制:", np.clip(arr, 6, 9))
print("四舍五入:", np.round(np.array([1.234, 2.567]), 1))